const TYPES = {
  ASIDE_TOGGLE: "ASIDE_TOGGLE",
  ASIDE_CHANGE: "ASIDE_CHANGE",
  BREADCRUMB_CHANGE: "BREADCRUMB_CHANGE",
  PAGE_CHANGE_HEADER_TITLE: "PAGE_CHANGE_HEADER_TITLE",
  PAGE_CHANGE_THEME: "PAGE_CHANGE_THEME",
  SIDEMENU_TOGGLE: "SIDEMENU_TOGGLE",
  SIDEMENU_CHANGE: "SIDEMENU_CHANGE",
  FIREBASE_CHANGE: "FIREBASE_CHANGE",
  ACTIVITY_CHANGE: "ACTIVITY_CHANGE",
  USER_CHANGE: "USER_CHANGE",
  PATHWAY_LOAD: "PATHWAY_LOAD",
  GET_PATHWAY: "GET_PATHWAY",
  RUNNER_LOAD: "RUNNER_LOAD",
  GET_RUNNER: "GET_RUNNER",

}

export default TYPES
